print("All measurements are in cm unless otherwise indicated")
gender = input("Enter your gender: (m/f/n)")
bideltoid = input("Enter your Bideltoid Shoulder Breadth: ")
hipB = input("Enter you Hip Breadth: ")
shoulderC = input("Enter your Shoulder Circumference: ")
waistC = input("Enter you Waist Circumference: ")
hipsC = input("Enter your Hips Circumference: ")
height = input("Enter you Height: ")

print(gender, bideltoid, hipB, shoulderC, waistC, hipsC, height)
